# Generated by Django 6.0.3 on 2026-04-16 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gasht_type', models.CharField(choices=[('public', 'উমুমী গাশত'), ('personal', 'খুসুসী গাশত')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gashts_as_amir', to='tablig.member')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gashts', to='tablig.area')),
                ('mutakallim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gashts_as_mutakallim', to='tablig.member')),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_gashts', to='tablig.member')),
                ('rahbar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gashts_as_rahbar', to='tablig.member')),
            ],
        ),
    ]
