# Generated by Django 6.0.3 on 2026-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablig', '0003_finance_jamat_talim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books_pdf/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
